### ISSUE TITLE
Reassign keyboard inputs

### ISSUE THREAD

**Issue by Beaulicious** [SEproject2025/project_wtc#90]

**Comment by prail** [comment]
@Beaulicious I am assuming that you did this?

**Comment by Beaulicious** [comment]
@prail No sir. I believe it was @stevennarvaez1 who completed this.

**Comment by Beaulicious** [comment]
But it is complete, nonetheless.

**Comment by prail** [comment]
Thanks for responding, I've assigned this to Steven then :)
